listen_addr = "127.0.0.1:8008"

[db]
url = "postgres://postgres:135246@127.0.0.1:5432/postgres"

[redis]
url = "redis://127.0.0.1:6379"
pool_size = 20
connection_timeout = 5000

[jwt]
secret = "yoursecret"
expiry = 3600
